# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function to calculate \phi(\Phi^{-1}(F(x)))
#'
#' @param x observed count
#' @param n total number of trials
#' @param p 0-1 range binomial probability
#' @param lg compute log-scale
#' @return \phi(\Phi^{-1}(F(x))) where F(x) = pbinom(x,n,p)
NULL

#' Internal function to calculate \phi(\Phi^{-1}(2*F(x))) or \phi(\Phi^{-1}(2(F(x)-F(0))/(1-F(0))))
#'
#' @param x observed count (smaller than median)
#' @param n total number of trials
#' @param p 0-1 range binomial probability
#' @param lg compute log-scale
#' @param pos_only consider positive values only
#' @param f0 Pr(X=0) or log Pr(X=0)
#' @return \phi(\Phi^{-1}(2*F(x))) (pos_only=false) or \phi(\Phi^{-1}(2(F(x)-F(0))/(1-F(0)))) (pos_only=true)
NULL

#' Internal function to calculate \phi(\Phi^{-1}(2*F_c(x))) or \phi(\Phi^{-1}(2(F_c(x))/(1-F(0))))
#'
#' @param x observed count (greater than median)
#' @param n total number of trials
#' @param p 0-1 range binomial probability
#' @param lg compute log-scale
#' @param pos_only consider positive values only
#' @param f0 Pr(X=0) or log Pr(X=0)
#' @return \phi(\Phi^{-1}(2*F_c(x))) (pos_only=false) or \phi(\Phi^{-1}(2(F_c(x))/(1-F(0)))) (pos_only=true)
NULL

#' Internal function to calculate \phi(\Phi^{-1}(q)
#'
#' @param q quantile value
#' @param lt quantile is lower tail
#' @param lg log-scale computation
#' @return \phi(\Phi^{-1}(q)
NULL

#' Function to calculate unidirectional z-score for single binomial distribution
#' 
#' @param x            observed count
#' @param n            total number of trials
#' @param p            0-1 ranged binomial probability
#' @param var_adj      perform variance adjustment if TRUE
#' @param approx_under threshold of binomial density to perform approximation during variance adjustment
#' @return A z-score corresponding to the input parameters
squat_single_binom_unidir <- function(x, n, p, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_single_binom_unidir`, x, n, p, var_adj, approx_under)
}

#' Function to calculate bidirectional z-score for single binomial distribution
#' 
#' @param x            observed count
#' @param n            total number of trials
#' @param p            0-1 ranged binomial probability
#' @param pos_only     ignore zeros if TRUE (x must be positive)
#' @param var_adj      perform variance adjustment if TRUE
#' @param approx_under threshold of binomial density to perform approximation during variance adjustment
#' @return A z-score corresponding to the input parameters
squat_single_binom_bidir <- function(x, n, p, pos_only = TRUE, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_single_binom_bidir`, x, n, p, pos_only, var_adj, approx_under)
}

#' A function to generate unidirectional z scores based on exact quantiles from binomial distribution
#' 
#' @param xs A integer vector containing the list of observed counts. 
#' @param sizes A integer vector containg the list of total counts. Must be the same length with xs or a constant
#' @param ps A numeric vector containing the binomial probability for each observations. Must be the same length with ps or a constant
#' @param var_adj Apply variance adjustment to improve power
#' @param approx_under Perform approximation in variance adjustment for Pr(X=x) smaller than the value
#' @return A vector of z-scores corresponding to expected aggregated z-scores from SQuAT
squat_multi_binom_unidir <- function(xs, sizes, ps, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_multi_binom_unidir`, xs, sizes, ps, var_adj, approx_under)
}

#' A function to generate bidirectional z scores based on exact quantiles from binomial distribution
#' 
#' @param xs A integer vector containing the list of observed counts. 
#' @param sizes A integer vector containg the list of total counts. Must be the same length with xs or a constant
#' @param ps A numeric vector containing the binomial probability for each observations. Must be the same length with ps or a constant
#' @param pos_only Ignore zeros in the distribution
#' @param var_adj Apply variance adjustment to improve power
#' @param approx_under Perform approximation in variance adjustment for Pr(X=x) smaller than the value
#' @return A vector of z-scores corresponding to expected overdispersion z-scores from SQuAT
squat_multi_binom_bidir <- function(xs, sizes, ps, pos_only = TRUE, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_multi_binom_bidir`, xs, sizes, ps, pos_only, var_adj, approx_under)
}

#' @title expt_truncated_gamma_from_qt
#' @description
#' Calculate expectation from truncated Gamma
#'
#' @param a lower quantile 
#' @param b upper quantile
#' @param lg compute log-scale
#' @return A single expected z-score for directional test 
expt_truncated_gamma_from_qt <- function(a, b, alpha, beta, lg = 0L, lower = 1L) {
    .Call(`_squat_expt_truncated_gamma_from_qt`, a, b, alpha, beta, lg, lower)
}

#' @title expt_truncated_bidir_gamma_from_qt
#' @description
#' Calculate expectation from truncated Gamma - folded
#'
#' @param ql lower quantile 
#' @param qu upper quantile
#' @param lg compute log-scale
#' @return A single expected z-score for overdispersion test 
expt_truncated_bidir_gamma_from_qt <- function(ql, qu, alpha, beta, lg = 0L, lower = 1L) {
    .Call(`_squat_expt_truncated_bidir_gamma_from_qt`, ql, qu, alpha, beta, lg, lower)
}

#' @title squat_single_binom_unidir_g
#' @description
#' Function to calculate unidirectional z-score for single binomial distribution using Gamma approximation
#' 
#' @param x            observed count
#' @param n            total number of trials
#' @param p            0-1 ranged binomial probability
#' @param alpha        shape parameter of the Gamma distribution 
#' @param beta         rate parameter of the Gamma distribution 
#' @param var_adj      perform variance adjustment if TRUE
#' @param approx_under threshold of binomial density to perform approximation during variance adjustment
#' @return A z-score and its standard deviation
squat_single_binom_unidir_g <- function(x, n, p, alpha, beta, var_adj = TRUE, approx_under = 1e-4, lower = TRUE) {
    .Call(`_squat_squat_single_binom_unidir_g`, x, n, p, alpha, beta, var_adj, approx_under, lower)
}

#' @title squat_multi_binom_dir_g
#' @description
#' A function to generate two sample directional z scores based on exact quantiles from binomial distribution
#' 
#' @param xs A integer vector containing the list of observed counts. 
#' @param sizes A integer vector containg the list of total counts. Must be the same length with xs or a constant
#' @param ps A numeric vector containing the binomial probability for each observations. Must be the same length with ps or a constant
#' @param ys A binary vector indicating two groups.
#' @param var_adj Apply variance adjustment to improve power
#' @param approx_under Perform approximation in variance adjustment for Pr(X=x) smaller than the value
#' @return A list including z-scores and its two moments 
squat_multi_binom_dir_g <- function(xs, sizes, ps, ys, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_multi_binom_dir_g`, xs, sizes, ps, ys, var_adj, approx_under)
}

