# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate unidirectional z-score for single binomial distribution
#'
#' @param x            observed count
#' @param n            total number of trials
#' @param p            0-1 ranged binomial probability
#' @param var_adj      perform variance adjustment if TRUE
#' @param approx_under threshold of binomial density to perform approximation during variance adjustment
#' @return A z-score corresponding to the input parameters
squat_single_binom_unidir <- function(x, n, p, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_single_binom_unidir`, x, n, p, var_adj, approx_under)
}

#' Function to calculate bidirectional z-score for single binomial distribution
#'
#' @param x            observed count
#' @param n            total number of trials
#' @param p            0-1 ranged binomial probability
#' @param pos_only     ignore zeros if TRUE (x must be positive)
#' @param var_adj      perform variance adjustment if TRUE
#' @param approx_under threshold of binomial density to perform approximation during variance adjustment
#' @return A z-score corresponding to the input parameters
squat_single_binom_bidir <- function(x, n, p, pos_only = TRUE, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_single_binom_bidir`, x, n, p, pos_only, var_adj, approx_under)
}

#' A function to generate unidirectional z scores based on exact quantiles from binomial distribution
#'
#' @param xs A integer vector containing the list of observed counts.
#' @param sizes A integer vector containg the list of total counts. Must be the same length with xs or a constant
#' @param ps A numeric vector containing the binomial probability for each observations. Must be the same length with ps or a constant
#' @param var_adj Apply variance adjustment to improve power
#' @param approx_under Perform approximation in variance adjustment for Pr(X=x) smaller than the value
#' @return A vector of z-scores corresponding to expected aggregated z-scores from SQuAT
squat_multi_binom_unidir <- function(xs, sizes, ps, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_multi_binom_unidir`, xs, sizes, ps, var_adj, approx_under)
}

#' A function to generate bidirectional z scores based on exact quantiles from binomial distribution
#'
#' @param xs A integer vector containing the list of observed counts.
#' @param sizes A integer vector containg the list of total counts. Must be the same length with xs or a constant
#' @param ps A numeric vector containing the binomial probability for each observations. Must be the same length with ps or a constant
#' @param pos_only Ignore zeros in the distribution
#' @param var_adj Apply variance adjustment to improve power
#' @param approx_under Perform approximation in variance adjustment for Pr(X=x) smaller than the value
#' @return A vector of z-scores corresponding to expected overdispersion z-scores from SQuAT
squat_multi_binom_bidir <- function(xs, sizes, ps, pos_only = TRUE, var_adj = TRUE, approx_under = 1e-4) {
    .Call(`_squat_squat_multi_binom_bidir`, xs, sizes, ps, pos_only, var_adj, approx_under)
}

